"""Phone number column editted

Revision ID: 119cb9dcf396
Revises: d4b06d76df67
Create Date: 2025-07-16 08:45:32.375559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119cb9dcf396'
down_revision = 'd4b06d76df67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_contact_info', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_contact_info', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
