"""Initial database setup 5

Revision ID: 1bae8a9c91ca
Revises: 125a991cbbd5
Create Date: 2025-07-11 10:17:11.901015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bae8a9c91ca'
down_revision = '125a991cbbd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_basic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('employee_contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_basic_info.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_salary_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('pay_grade', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_basic_info.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_salary_info')
    op.drop_table('employee_contact_info')
    op.drop_table('employee_basic_info')
    # ### end Alembic commands ###
