"""Initial database setup 6

Revision ID: d4b06d76df67
Revises: 1bae8a9c91ca
Create Date: 2025-07-11 10:44:29.354430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b06d76df67'
down_revision = '1bae8a9c91ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_contact_info', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('employee_salary_info', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('pay_grade',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_salary_info', schema=None) as batch_op:
        batch_op.alter_column('pay_grade',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    with op.batch_alter_table('employee_contact_info', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
