"""Initial migrate

Revision ID: e64c6e5ef9ae
Revises: 
Create Date: 2025-08-07 01:33:12.914676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64c6e5ef9ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_basic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('employee_contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_basic_info.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_salary_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('pay_grade', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_basic_info.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_salary_info')
    op.drop_table('employee_contact_info')
    op.drop_table('employee_basic_info')
    # ### end Alembic commands ###
